### ISSUE TITLE
Issue with current image centos:8 build

### ISSUE THREAD

**Issue by Luwdo** [davidalger/docker-images-php#12]
It looks like the maintainers of centos:8 images have some urgent updates causing epel mirror checksums to fail without the latest.

```docker run -it --rm davidalger/php:7.4-fpm dnf update```

This will fail at the moment with 

```Error: Failed to download metadata for repo 'epel': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried```

Looks like there is a fix in latest 8 tag

```docker run -it --rm centos:8 dnf update```

If you could manually trigger your git workflow CI to get the update, much appreciated.

**Comment by davidalger** [comment]
@Luwdo They are rebuilding now: https://github.com/davidalger/docker-images-php/actions/runs/1309650119

**Comment by mr-pmillz** [comment]
After pulling the latest php:7.4-fpm release just now that the build trigger pushed, I am still getting the same error. 🤔 

```shell
❯ docker run -it --rm davidalger/php:7.4-fpm dnf update
CentOS Linux 8 - AppStream                                                                                                   5.1 MB/s | 9.3 MB     00:01
CentOS Linux 8 - BaseOS                                                                                                      4.1 MB/s | 7.5 MB     00:01
CentOS Linux 8 - Extras                                                                                                       19 kB/s |  10 kB     00:00
Extra Packages for Enterprise Linux Modular 8 - x86_64                                                                       1.4 MB/s | 956 kB     00:00
Extra Packages for Enterprise Linux 8 - x86_64                                                                               1.4 kB/s | 4.7 kB     00:03
Errors during downloading metadata for repository 'epel':
  - Downloading successful, but checksum doesn't match. Calculated: 9719bd3e7d8f3a217103b14eb122758d3d3a086a6a46eeeab953017a4a5907f9e96079b7faec9a7f836571713ce25d14e94abd8b7709a8717b78b8292221a621(sha512) 9719bd3e7d8f3a217103b14eb122758d3d3a086a6a46eeeab953017a4a5907f9e96079b7faec9a7f836571713ce25d14e94abd8b7709a8717b78b8292221a621(sha512)  Expected: d7866fd1604ef749ced5df995dfa050d491a4cf642c7b81797d5da38e6e80829758956deaec02405ab2dbcecff8cd6dcdb13b5559198101fd965daa1958e8500(sha512) be6e8f5d423e9a31310dd5a6450097c2a1253efeffd54ebcae0ded443e878feb851304ae77130f16ac021b27850c5ee83444f4e6650cad926684beb7648fc471(sha512)
Error: Failed to download metadata for repo 'epel': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

```

**Comment by Luwdo** [comment]
Well now that is strange, I saw a recent update in centos:8 and assumed that was the issue they solved just from a quick sanity check with the base image. 

I don't see anything in the Dockerfile's that would cause these images to fail checksums for the epel repo metadata for subsequent updates.

This is eerily similar to an issue we are seeing with nodesource where certain regions CDNs had updated metadata from akamai and they forgot to resign so you get checksum errors.

I should be able to pull this repo down and build locally.

**Comment by Luwdo** [comment]
Ok good, booted a ec2 to test build on an isolated network. Same error, I'll do some more testing see if I can narrow down whats doing it.

**Comment by Luwdo** [comment]
Well ok now, thanks for running the update on the images, after doing some testing. This issue has to be an epel-release repo bug.

```
docker run -it --rm centos:8 /bin/bash
dnf install -y epel-release
dnf install -y epel-release
```

The second install will cause the same checksum issue.

**Comment by Luwdo** [comment]
same issue with bypassing the mirrors
```
dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
```

**Comment by mr-pmillz** [comment]
appears to be working now

**Comment by Luwdo** [comment]
Yep the maintainers of the epel RPM repo appears to have fixed their issue.
